from collections import Counter
import statistics
from tenx.engine import _run_decision_core
from empirical.backbone import run_empirical_reference
SEEDS=[6,10,18,26,38,50,62]
def run_campaign():
    runs=[_run_decision_core(s) for s in SEEDS]; sets=[tuple(sorted(r['decision']['selected_lines'])) for r in runs]; modal,n=Counter(sets).most_common(1)[0]; exposure=[]
    for r in runs:
        selected=set(r['decision']['selected_lines']); e=sum(float(x['risk'])*float(x['escape_cost']) for x in r['decision']['ranked'] if x['line'] not in selected); exposure.append(e)
    brier=[r['model_validation']['value'] for r in runs]; emp=run_empirical_reference(); meanexp=statistics.mean(exposure); state='CONTAINMENT_POLICY_REVIEW' if n/len(runs)>=.7 and max(brier)<.22 else 'HOLD_AND_REASSESS'
    return {'campaign':'Adaptive Quality Containment Campaign','campaign_identity':'expected escape exposure + measurement-value frontier','scenario_count':len(runs),'scenario_seeds':SEEDS,'state':state,'modal_selected_lines':list(modal),'selection_share':round(n/len(runs),4),'expected_uninspected_escape_cost':round(meanexp,2),'worst_uninspected_escape_cost':round(max(exposure),2),'mean_brier_score':round(statistics.mean(brier),5),'scenario_matrix':[{'seed':s,'selected_lines':r['decision']['selected_lines'],'minutes_used':r['decision']['minutes_used'],'capacity':r['decision']['capacity'],'uninspected_escape_exposure':round(exposure[i],2),'brier':brier[i]} for i,(s,r) in enumerate(zip(SEEDS,runs))],'ai_synthesis':{'why':f'{list(modal)} is modal in {n}/{len(runs)} campaigns; mean residual expected escape exposure={meanexp:.1f} reference cost units.','challenge':'Highest predicted risk is not automatically inspection-worthy when the gage cannot discriminate.','recommended_operator_action':'Review residual escape exposure and measurement evidence before enabling adaptive containment.','abstention_conditions':['gage discrimination inadequate','capacity insufficient','defect model drift','belief state invalid']},'action_queue':['inspect defect-risk stratification','verify MSA/gage discrimination','review GAGE-SHIELD allocation','escalate persistent policy to ECON-SPC-P','approve or modify containment plan'],'human_authority':'QUALITY_ENGINEER','autonomous_execution':False,'empirical_provenance':{'mode':emp.get('data_mode'),'promotion':emp.get('empirical_promotion')}}
